import "../bin/libs/min/laya.core.min"; 
import "../bin/libs/min/laya.ui.min";
import "../bin/libs/min/laya.wxmini.min";
import Sprite = Laya.Sprite;
import Box = Laya.Box;
import Image = Laya.Image;
import Event = Laya.Event;
import WebGL = Laya.WebGL;
import Handler = Laya.Handler;
import Stage = Laya.Stage;
import Text = Laya.Text;
import Tween = Laya.Tween;
import Stat = Laya.Stat;
import Utils = Laya.Utils;
import List = Laya.List;
const wx = (window as any)["wx"];
const sharedCanvas = (window as any)["sharedCanvas"];
import MiniAdpter = Laya.MiniAdpter;
import Matrix = Laya.Matrix;
export { Sprite, Event, WebGL, Handler, Stage, Text, Tween, Stat, Utils, MiniAdpter, Box, Image, wx, List, Matrix, sharedCanvas}